version: '3.8'

services:
  mongodb:
    image: mongo:7
    container_name: workshop-mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: workshop
      MONGO_INITDB_ROOT_PASSWORD: workshop123
      MONGO_INITDB_DATABASE: workshop
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - workshop-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: workshop-backend
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - DATABASE_URL=mongodb://workshop:workshop123@mongodb:27017/workshop?authSource=admin
      - JWT_SECRET=your-jwt-secret-change-in-production
      - PORT=3001
    ports:
      - "3001:3001"
    depends_on:
      - mongodb
    networks:
      - workshop-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: workshop-frontend
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - API_URL=http://backend:3001
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - workshop-network

volumes:
  mongodb_data:

networks:
  workshop-network:
    driver: bridge
